### ISSUE TITLE
update to cats-1.0.0-rc1

### ISSUE THREAD

**Issue by tpolecat** [julien-truffaut/newts#22]
I'll do this one.

**Comment by pettyjamesm** [comment]
Bump. Can we get the cats dependency version up to 1.1.0 ? I noticed it was transitively depending on 1.0.0 while trying to rebuild Monocle with cats 1.1.0

**Comment by torgeirsh** [comment]
It seems like no code changes are required for 1.2.0. Would it be possible to make a release for that?

**Comment by julien-truffaut** [comment]
@torgeirsh cats is binary compatible for all 1.x, why do you need a release of newts?

**Comment by torgeirsh** [comment]
I see, maybe I don't need it then? Was just worried about the noisy eviction warnings from SBT, and thought new builds of Newts and Monocle would be necessary.

**Comment by julien-truffaut** [comment]
@torgeirsh Yes I don't think you need the upgrade
